server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/people_system?allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  show_sql: true

